### PR TITLE
1.20.1 fixes

### PR DESCRIPTION
**Pull request by Smartin-b**
- ported to 1.20.1
- removed your stuff in the gradles for private testing

### CODE REVIEW

**Comment by OroArmor** [comment]
Do you still actively use Oro-Config? I havent updated this mod in ages since I no longer use it and there are better options for config.

**Comment by Smartin-b** [comment]
well, i was looking for a platform independent light weight config, since im working on a architectury mod.
i ended up including oroconfig manually at the moment https://github.com/Truly-Modular/Modular-Item-API/tree/main/common/src/main/java/smartin/miapi/config/oro_config
i didnt want to have more external dependencies, thats why i choose oro config.
since i already done the porting i figured i could make a pr as well.

**Comment by OroArmor** [comment]
while im not 100% sure, i think https://github.com/Fuzss/forgeconfigapiport is a better option. especially since this mod is not as lightweight as i once thought it to be.

**Comment by Smartin-b** [comment]
well, yes, but forgeconfigapiport would be a external dependency, and i wanted to avoid those for the time being.
and wdym this sint as lightweight as you thought?

**Comment by Smartin-b** [comment]
like i said, i wanted something that works on fabric and forge, server and client, and does not require users to download a seperate jar, and oro config was the first thing i found that looked decent

**Comment by OroArmor** [comment]
Makes sense. Ill merge this but i wont publish to maven central as the system i made for it broke. You can use jitpack to build it or do something locally

**Pull request merged**
